FROM toshiara/texlive-ja:2022.8.13

RUN tlmgr update --self --all && \
    tlmgr install \
        ccicons fourier fouriernc inconsolata \
        lxfonts newtx newtxsf newpx \
        noto opensans roboto \
        siunitx stix yhmath \
        libertine libertinus-fonts libertinus-type1 \
        libertinust1math \
        stix2-otf stix2-type1 asana-math xits

